version: '3'
services:

  # Front End

  score-web:
    build: .
    volumes:
      - . /apps
      - score-data:/app
    ports:
      - 8777:8777
    image: thanevil/worldofgames:latest

    # Database Service (Mysql)

  mysqldb:
    image: mysql/mysql-server:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - score-data:/var/lib/mysql
volumes:
  score-data:
